### ISSUE TITLE
env: python: No such file or directory

### ISSUE THREAD

**Issue by AmitayKaufmamn** [pygments/pygments.rb#241]
Hey,
We are using Pygments for a while now. 
Lately, we started getting this error when using Pygments localy:

`env: python: No such file or directory`

![image](https://user-images.githubusercontent.com/88721320/173234519-5020bf45-35c7-4497-9fe8-d6a0abec8c30.png)

Any idea what can be the cause? Thanks.

**Comment by slonopotamus** [comment]
What pygments.rb version you're using? You might want updating because there was a Python 2 -> Python 3 migration in [v2.0.0](https://github.com/pygments/pygments.rb/releases/tag/v2.0.0).

**Comment by AmitayKaufmamn** [comment]
Thank you @slonopotamus 
Ill check this direction.
