### ISSUE TITLE
`guess()` from Ruby

### ISSUE THREAD

**Issue by verhovsky** [pygments/pygments.rb#260]
I wanted to print what Pygments guesses a language would be, but these bindings don't include that function.

ChatGPT hallucinated this

```ruby
      guessed_lexer = Pygments.lexers.guess(code: code)
```

and I think that makes sense.

**Comment by slonopotamus** [comment]
You can use `P.lexer_names_for` for this. See examples: https://github.com/pygments/pygments.rb/blob/v2.4.1/test/test_pygments.rb#L132-L138
