### ISSUE TITLE
Update Pygments

### ISSUE THREAD

**Issue by verhovsky** [pygments/pygments.rb#261]
Please make a new release with Pygments 2.18.0

**Comment by slonopotamus** [comment]
You're welcome: https://github.com/pygments/pygments.rb/releases/tag/v3.0.0

**Comment by verhovsky** [comment]
Thanks, now Nix looks normal

https://web.archive.org/web/20240509001515/https://learnxinyminutes.com/docs/nix/

https://learnxinyminutes.com/docs/nix/
